### ISSUE TITLE
Store manifests in the reporting cluster

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/platform#4521]
Follows https://github.com/wellcomecollection/platform/issues/4410

We're going to do away with the `files` index, and just have a `bags` index. This is the schema:

```
Bag
    - space: String
    - externalIdentifier: String
    - version: Int
    - createdDate: String
    - payloadFiles: Seq[File]
    - payloadFileCount: Int
    - payloadFileSize: Int
    - payloadFileSuffixTally: Map[String, Int]
    - newPayloadFileCount: Int
    - newPayloadFileSize: Int
    - newPayloadFileSuffixTally: Map[String, Int]
File:
    - path: String
    - name: String
    - size: Int
    - checksum: String
```

Notes:

* We exclude manifest files (e.g. `manifest-sha256.txt`) from the tally. We only count payload files.
* The `new*` field counts everything new to this bag – stuff fetched from a previous version doesn’t count.
